repos:
  - repo: local
    hooks:
      - id: build-dist
        name: Build dist
        entry: bash build.sh
        language: system
        files: '\.(html|typ)$'
        pass_filenames: false
        stages: [pre-commit]
